const FAIL_FETCH_INFORMATION = 'FAIL_FETCH_INFORMATION';
const SUCSESS_FETCH_INFORMATION = 'SUCSESS_FETCH_INFORMATION';
const CLOSE_FETCH_ERROR = 'CLOSE_FETCH_ERROR';
const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';
const CHANGE_FAVORITE_ITEM = 'CHANGE_FAVORITE_ITEM';

export {
  CLOSE_FETCH_ERROR,
  FAIL_FETCH_INFORMATION,
  SUCSESS_FETCH_INFORMATION,
  ADD_TO_FAVORITE,
  REMOVE_FROM_FAVORITE,
  CHANGE_FAVORITE_ITEM,
};
